"""
models/claim.py
───────────────
Automated claim generated by ClaimsAgent when a trigger fires.
No manual submission needed — the system creates claims automatically.
"""

from datetime import datetime, timezone
from sqlalchemy import String, Float, DateTime, ForeignKey, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from database.db import Base


class Claim(Base):
    __tablename__ = "claims"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)

    # ── Foreign keys ──────────────────────────────────────────────────────────
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), nullable=False, index=True)
    policy_id: Mapped[int] = mapped_column(ForeignKey("policies.id"), nullable=False, index=True)

    # ── What triggered this claim ─────────────────────────────────────────────
    trigger_type: Mapped[str] = mapped_column(String(50), nullable=False)  # rain | aqi | heat
    trigger_city: Mapped[str] = mapped_column(String(80), nullable=False)

    # ── Payout info ───────────────────────────────────────────────────────────
    payout_amount: Mapped[float] = mapped_column(Float, nullable=False)  # ₹

    # ── Processing state ──────────────────────────────────────────────────────
    status: Mapped[str] = mapped_column(
        String(30), default="pending"
    )  # pending | approved | paid | rejected

    # ── AI reasoning note ─────────────────────────────────────────────────────
    ai_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        index=True,
    )
    processed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    user: Mapped["User"] = relationship("User", back_populates="claims")    # noqa: F821
    policy: Mapped["Policy"] = relationship("Policy", back_populates="claims")  # noqa: F821

    def __repr__(self) -> str:
        return (
            f"<Claim id={self.id} user_id={self.user_id} "
            f"payout=₹{self.payout_amount} status={self.status!r}>"
        )
